name: Waka Readme

on:
  schedule:
    # Runs at 12am IST
    - cron: '30 18 * * *'
  workflow_dispatch:
jobs:
  update-readme:
    name: Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: 232f87d3-f0fe-4498-a952-45d1e65e1781
          GH_TOKEN: 8f3d37801ae844b95b41bf4f3ce0b7b9bc0110a2
